# Docker Compose file for MindsDB Demo Studio
# See https://github.com/tbaums/mindsdb-demo-studio

services:
  mindsdb:
    container_name: mindsdb
    image: mindsdb/mindsdb
    ports:
      - "47334:47334"
    networks:
      - demo

  redpanda:
    container_name: redpanda
    image: vectorized/redpanda
    ports:
      - "9092:9092"
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 0
      - --check=false
    networks:
      - demo

  cassandra:
    container_name: cassandra
    image: cassandra:latest
    ports:
      - "9042:9042"
    networks:
      - demo

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    networks:
      - demo
  
  ollama:
    container_name: ollama
    image: ollama/ollama
    ports:
      - "11434:11434"
    networks:
      - demo

networks:
  demo:
    driver: bridge
